server:
  port: 8080
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: demo1
#          url: http://localhost:8081/
#          predicates:
#            - Path=/demo1/**
#        - id: demo2
#          url: http://localhost:8082/
#          predicates:
#            - Path=/demo2/**